name: static pages

on:
    push:
        branches:
            - master
        paths:
            - docs/**

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Upload pages artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  name: github-pages
                  path: docs
    deploy:
        needs: build
        runs-on: ubuntu-latest

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy pages
              uses: actions/deploy-pages@v2
              id: deployment
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
