name: TypeScript quality checks

on:
    pull_request:
        branches:
            - master
        paths:
            - "typescript/src/**"
            - "typescript/package.json"
            - "typescript/tsconfig.json"
            - ".github/workflows/typescript-quality.yml"
    push:
        branches:
            - master
        paths:
            - "typescript/src/**"
            - "typescript/package.json"
            - "typescript/tsconfig.json"
            - ".github/workflows/typescript-quality.yml"
    workflow_dispatch:
        inputs:
            pr_number:
                description: "PR number to run coverage for"
                required: false
                type: string

permissions:
    contents: read
    pull-requests: write
    actions: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: install
              working-directory: ./typescript
              run: bun install

            - name: typecheck
              working-directory: ./typescript
              run: bun run typecheck

            - name: test
              working-directory: ./typescript
              run: bun run test

            - name: Coverage report
              if: (github.event_name == 'pull_request' && github.actor != 'release-please[bot]') || github.event_name == 'workflow_dispatch'
              uses: xseman/coverage@v0.3.0
              with:
                  pull-request-number: ${{ github.event.inputs.pr_number }}
                  update-comment-marker: "<!-- coverage-reporter-ts -->"
                  coverage-artifact-paths: |
                      bun:typescript/coverage/lcov.info

    fmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: install
              working-directory: ./typescript
              run: bun install

            - name: format check
              working-directory: ./typescript
              run: bun fmt:check
